In [269]:
import numpy as np 
import pandas as pd

np.random.seed(42)

In [270]:
class Layer:
     
    def __init__(self, input_size, output_size): 
        
        self.inputs = None 
        self.weight = np.random.randn(output_size, input_size)
        self.bias = np.zeros(shape=(output_size, 1))
        self.output = None 
        
        # derivived instance field 
        self.d_bias = None 
        self.d_weight = None 
        self.d_output = None 
        self.d_input = None 
        
    def forward_pass(self, input):
        self.inputs = input 
        output = np.dot(self.weight , self.inputs) + self.bias
        
        # Clipping the output so that it doesn't overflow when passed into an activation function
        self.output = np.round(output, 5)
        return self.output
        

    def backward_pass(self, d_values): 
        
        self.d_weight = np.dot(self.inputs.T)
        self.d_bias 
        self.d_inputs
        pass
        
    def show_attribute(self): 
        print("Input  : \n", self.inputs)
        print("Weight : \n", self.weight)
        print("Biases : \n", self.bias) 
        print("Output : \n", self.output)

In [271]:

class Activation_Function: 
    
    # Passing in the array/s into the function  
    def tanh_activation_function(self, input): 
        output = np.round(((np.exp(input)) - np.exp(-input)) / ((np.exp(input)) + np.exp(-input)), 5)
        return output 
    
    def d_tanh_activation_function(self, input): 
        output = 1 - ((np.exp(input) - np.exp(-input))**2 / (np.exp(input) + np.exp(-input))**2) 
        return output 
    
    def sigmoid_activation_function(self, input): 
        output = 1/(1 + np.exp(-(input)))
        return output 

In [272]:
class Binary_Cross_Entropy: 
    
    def binary_cross_entropy(self, y_pred, y_true):
        
        # Calculate binary cross entropy loss
        self.loss = -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
        
        return self.loss 

In [273]:
class Mean_Squared_Error: 

    def mean_squared_error(self, y_pred, y_true):
        
        if y_pred.ndim != 1: 
            summed_matrix = y_pred.sum(axis=0)
        else:
            summed_matrix = y_pred 
        self.loss = np.mean((y_true - summed_matrix)**2)
         
        return  self.loss
    

In [274]:
class Stocastic_Gradient_Descent: 
    
    # By default the learning rate is set to one unless its specified 
    def __init__(self, learning_rate=1.0 ):
        self.learning_rate = learning_rate 
        
    def update_parameters(self, layer): 
        layer.weight += -self.learning_rate * layer.d_weight 
        layer.bias += -self.learning_rate * layer.d_bias 
    
    def forward(self): 
        pass 
    
    def backward(self): 
        pass 

        d_loss_output = -2 * (y_true - self.output) 
        d_output_weighted_sum = 1 - ((np.exp(self.output) - np.exp(-self.output))**2 / (np.exp(self.output) + np.exp(-self.output))**2) 
        
        self.d_weight = np.dot((d_loss_output * d_output_weighted_sum ).reshape(-1, 1), self.inputs.reshape(1, -1))
        self.d_bias = d_loss_output * d_output_weighted_sum

        return self.d_weight, self.d_bias
    
    def gradient_descent(self, learning_rate=0.01): 
        self.weight -= learning_rate * self.d_weight 
        self.bias -= learning_rate * self.d_bias.reshape(-1, 1) 

In [275]:
y_true = [1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0]

x_input = [ 1.0, -1.0,  1.0,  1.0,  1.0,  1.0, -1.0,  1.0,  1.0, -1.0], [-1.0, -1.0,  1.0, -1.0, -1.0, -1.0,  1.0,  1.0, -1.0, -1.0], [ 1.0,  1.0, -1.0,  1.0, -1.0,  1.0, -1.0,  1.0, -1.0,  1.0] , [ 1.0, -1.0,  1.0, -1.0,  1.0, -1.0, -1.0,  1.0, -1.0,  1.0]

# Forward Pass

In [276]:
# Layer(input, output size)
input_layer = Layer(4, 12)
hidden_layer_1 = Layer(12, 12) 
hidden_layer_2 = Layer(12, 8) 
hidden_layer_3 = Layer(8, 6)
output_layer = Layer(6, 4)

In [277]:
# Creating Necessary Objects 
activation = Activation_Function()
loss_activation = Binary_Cross_Entropy() 

In [278]:
# By calling the activation function on the ouput of the current layer it updates the output. 
input_layer.forward_pass(x_input)
input_layer.output = activation.sigmoid_activation_function(input_layer.output) 

hidden_layer_1.forward_pass(input_layer.output)
hidden_layer_1.output = activation.sigmoid_activation_function(hidden_layer_1.output)

hidden_layer_2.forward_pass(hidden_layer_1.output)
hidden_layer_2.output = activation.sigmoid_activation_function(hidden_layer_2.output)

hidden_layer_3.forward_pass(hidden_layer_2.output)
hidden_layer_3.output = activation.sigmoid_activation_function(hidden_layer_3.output) 

output_layer.forward_pass(hidden_layer_3.output)
output_layer.output = activation.sigmoid_activation_function(output_layer.output) 


In [279]:
output_layer.output

array([[0.24058956, 0.22014527, 0.24280724, 0.22586129, 0.23499107,
        0.22586129, 0.21988443, 0.2431052 , 0.22283346, 0.24000173],
       [0.06859529, 0.07148758, 0.07721661, 0.06621742, 0.08292292,
        0.06621742, 0.08072255, 0.06184233, 0.07640257, 0.08091421],
       [0.84153982, 0.84569009, 0.83782184, 0.84804252, 0.82326693,
        0.84804252, 0.84096022, 0.85419508, 0.83709222, 0.83231727],
       [0.18828233, 0.20751664, 0.19348227, 0.19734366, 0.2033916 ,
        0.19734366, 0.21422393, 0.18240464, 0.20986655, 0.19875721]])

In [237]:
# Since the final output would be viewed as predictions, we will convert all negatives to 0 and all positives to 1
processed_array = np.where(output_layer.output > 0, 1, 0)
summed_array = np.sum(processed_array, axis=0)
bool_array = np.where((summed_array == 0) | (summed_array == 1), False, True)
accuracy = np.mean(bool_array == y_true)



In [254]:
output_layer.output

array([[ 0.99436,  0.79552, -0.79552,  0.96657,  0.99266,  0.96657,
        -0.99436,  0.3868 ,  0.91767,  0.61439],
       [-0.1666 , -0.99977,  0.99977,  0.49259, -0.74627,  0.49259,
         0.1666 ,  0.99283, -0.98228, -0.99987],
       [ 0.73905,  0.53   , -0.53   ,  0.95931,  0.9413 ,  0.95931,
        -0.73905, -0.68259,  0.81846,  0.39521],
       [ 0.76322,  0.47334, -0.47334,  0.75914,  0.93303,  0.75914,
        -0.76322,  0.13153,  0.74786,  0.31893]])

In [256]:
np.log(np.round(output_layer.output,3))

/var/folders/80/yxql_m2n3b93pljkxwjyygr40000gn/T/ipykernel_66629/931077132.py:1: RuntimeWarning: invalid value encountered in log
  np.log(np.round(output_layer.output,3))


array([[-0.00601807, -0.22815609,         nan, -0.03355678, -0.00702461,
        -0.03355678,         nan, -0.94933059, -0.08555789, -0.48776035],
       [        nan,         nan,  0.        , -0.7072461 ,         nan,
        -0.7072461 , -1.78976147, -0.00702461,         nan,         nan],
       [-0.30245736, -0.63487827,         nan, -0.0418642 , -0.06081214,
        -0.0418642 ,         nan,         nan, -0.20089294, -0.92886951],
       [-0.27049725, -0.74865989,         nan, -0.2757535 , -0.06935008,
        -0.2757535 ,         nan, -2.02495336, -0.2903523 , -1.14256418]])

In [238]:
# Calling a function to compute the loss 
loss = loss_activation.binary_cross_entropy(output_layer.output, y_true)

# Here we are finding the accuracy. 
# Since the final output would be viewed as probability, we will essentially convert all negatives to false and all positives to true
processed_array = np.where(output_layer.output > 0, 1, 0)
summed_array = np.sum(processed_array, axis=0)
bool_array = np.where((summed_array == 0) | (summed_array == 1), False, True)
accuracy = np.mean(bool_array == y_true)
    
print("Loss: ", loss) 
print("Accuracy: ", accuracy)



TypeError: unsupported operand type(s) for -: 'int' and 'list'

# Backward Pass

In [ ]:
optimizer = Stocastic_Gradient_Descent()

In [ ]:
loss_activation.backward(output_layer.output, layer)

In [ ]:


optimizer.update_parameters(input_layer)
optimizer.update_parameters(hidden_layer_1)
optimizer.update_parameters(hidden_layer_2)
optimizer.update_parameters(hidden_layer_3)
optimizer.update_parameters(output_layer)


TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

In [ ]:
for epochs in range(100): 
    print("step ", epochs, ". Loss: ", ", Accuracy: " )
    pass 
