In [185]:
import numpy as np 
import pandas as pd

np.random.seed(42)

In [226]:
class MLP: 
    
    def __init__(self, batch_size_inputs): 
        self.layer = None
        self.batch_size_inputs = batch_size_inputs 
        
    def forward_pass(self):
        self.layer = self.batch_size_inputs 
        layer_output = []
        for layers in self.batch_size_inputs: 
            layer_output.append(Layer.forward_pass(layers))
        
        return print(layer_output)

class Layer:
     
    def __init__(self, input_size, output_size): 
        
        self.inputs = None 
        self.weight = np.random.randn(output_size, input_size)
        self.bias = np.zeros(shape=(output_size, 1))
        self.output = None 
        
        # derivived instance field 
        self.d_bias = None 
        self.d_weight = None 
    
    def show_attribute(self): 
        print("Input  : \n", self.inputs)
        print("Weight : \n", self.weight)
        print("Biases : \n", self.bias) 
        print("Output : \n", self.output)
        
    def tanh_activation_function(self, input): 
        output = ((np.exp(input)) - np.exp(-input)) / ((np.exp(input)) + np.exp(-input)) 
        return output 
        
    def forward_pass(self, input):
        self.inputs = input 
        weighted_sum = np.dot(self.weight , self.inputs) + self.bias 
        self.output = self.tanh_activation_function(weighted_sum)
        return self.output
        
        # return self.output.flatten() 
    
    def mean_squared_error(self, y_true):
        self.loss = np.mean((y_true - self.output)**2)
        print(y_true - self.output)
        print((y_true - self.output)**2) 
        return  self.loss
    
    def backward_pass(self, y_true): # Compute the loss function with respect to each weight. 
        d_loss_output = -2 * (y_true - self.output) 
        d_output_weighted_sum = 1 - ((np.exp(self.output) - np.exp(-self.output))**2 / (np.exp(self.output) + np.exp(-self.output))**2) 
        
        self.d_weight = np.dot((d_loss_output * d_output_weighted_sum ).reshape(-1, 1), self.inputs.reshape(1, -1))
        self.d_bias = d_loss_output * d_output_weighted_sum

        return self.d_weight, self.d_bias
    
    def gradient_descent(self, learning_rate=0.01): 
        self.weight -= learning_rate * self.d_weight 
        self.bias -= learning_rate * self.d_bias.reshape(-1, 1) 
    
    


In [227]:
y_true = [1.0, 2.0, 3.0, 4.0]
x_input = [-1.0, 7.0, 2.0, -4.0], [-1.0, 6.0, 9.0, -4.0], [-2.0, -3.0, 2.0, -5.0] , [7.0, 3.0, 2.0, 0.0]

In [232]:
# Layer(input, output size)
input_layer = Layer(4, 6)
hidden_layer_1 = Layer(6, 12) 
hidden_layer_2 = Layer(12, 8) 
hidden_layer_3 = Layer(8, 6)
output_Layer = Layer(6, 4)

In [233]:
output_1 = input_layer.forward_pass(x_input)
output_1

array([[ 0.99938054, -0.9998414 , -1.        ,  0.99999665],
       [-1.        ,  1.        ,  1.        , -1.        ],
       [-0.99899656, -1.        , -1.        ,  0.99999972],
       [-0.99979021,  0.91446182, -0.99980576, -0.70620405],
       [ 0.54857435,  0.99999886,  0.99998438, -1.        ],
       [-1.        , -0.88040004,  0.83816748, -0.99995687]])

In [238]:
input_layer.show_attribute()

Input  : 
 ([-1.0, 7.0, 2.0, -4.0], [-1.0, 6.0, 9.0, -4.0], [-2.0, -3.0, 2.0, -5.0], [7.0, 3.0, 2.0, 0.0])
Weight : 
 [[ 0.57312781 -1.78586649 -0.35962967  0.30110734]
 [ 0.18383452  2.69303366  0.34980002 -1.0040546 ]
 [-0.09546425 -1.77624633 -0.08059975 -0.83305606]
 [ 0.91539028 -0.54954027 -0.11676592 -0.63555784]
 [ 1.73885135 -0.32124277  1.83255704  0.81415176]
 [ 0.48206673  0.36873315  0.3937973  -1.92767258]]
Biases : 
 [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Output : 
 [[ 0.99938054 -0.9998414  -1.          0.99999665]
 [-1.          1.          1.         -1.        ]
 [-0.99899656 -1.         -1.          0.99999972]
 [-0.99979021  0.91446182 -0.99980576 -0.70620405]
 [ 0.54857435  0.99999886  0.99998438 -1.        ]
 [-1.         -0.88040004  0.83816748 -0.99995687]]


In [234]:
output_2 = hidden_layer_1.forward_pass(output_1)
output_2

array([[-0.8859938 , -0.93086046,  0.99926436, -0.95004226],
       [ 0.61306957, -0.99812348, -0.99968161,  0.99993239],
       [ 0.94653925, -0.88422257,  0.9620855 , -0.93843672],
       [ 0.99997127, -0.9146008 , -0.57768785,  0.99792643],
       [ 0.99448093, -0.92520989, -0.73880922,  0.98560684],
       [ 0.59368219,  0.99967206,  0.99555778, -0.9975264 ],
       [-0.98976227, -0.8999886 , -0.7666033 ,  0.53890556],
       [-0.89702305,  0.77608077,  0.10069085,  0.5135675 ],
       [-0.79185599,  0.1765367 , -0.93588599,  0.76840946],
       [ 0.99305178, -0.0953743 ,  0.69662166,  0.29937717],
       [-0.75087559, -0.82265009, -0.9939574 ,  0.97572418],
       [ 0.28721087,  0.99982319,  0.26564868, -0.52328767]])

In [235]:
output_3 = hidden_layer_2.forward_pass(output_2)
output_3

array([[ 0.99479133, -0.00573557,  0.99064672, -0.94087567],
       [ 0.97243241,  0.99997158,  0.77722672, -0.75327516],
       [ 0.97839798,  0.06170154,  0.17792863,  0.35160547],
       [-0.91599181,  0.19669468,  0.99983673, -0.99964075],
       [-0.58296598, -0.99986227, -0.90750154, -0.96999551],
       [ 0.97402784, -0.99999448, -0.99962438,  0.99948421],
       [ 0.8420076 ,  0.95421205,  0.99999837, -0.99992153],
       [-0.39211116, -0.38736141,  0.99943097, -0.99977717]])

In [236]:
output_4 = hidden_layer_3.forward_pass(output_3)
output_4

array([[ 0.79035661,  0.95001392,  0.71575798, -0.22564777],
       [-0.86075184,  0.37042643,  0.99705021,  0.44824788],
       [-0.4936835 , -0.99302202, -0.84181942, -0.50275074],
       [-0.99999652,  0.98622564,  0.99376173, -0.41128556],
       [-0.02012256,  0.96383247,  0.99981127, -0.85984821],
       [-0.99865523,  0.16486263, -0.46462059, -0.93422584]])

In [237]:
final_output = output_Layer.forward_pass(output_4)
final_output

array([[ 0.09510344,  0.80192845,  0.78835529,  0.05130965],
       [ 0.87477327, -0.9728949 , -0.90868003,  0.03419143],
       [ 0.90163149,  0.8015105 ,  0.96565777,  0.98375098],
       [ 0.98898151,  0.69635198,  0.040231  ,  0.67671552]])

loss = 

In [180]:
output_1 = input_layer.forward_pass(x_input)

AttributeError: 'tuple' object has no attribute 'T'

In [147]:
input_layer.inputs , input_layer.weight.shape

([-1.0, 7.0, 2.0, -4.0], (6, 4))

________________
PIVOT

In [148]:
#Creating an Input Layer of 4 inputs feeding forward into 7 neurons
layer_1_size = 7
inputs = ([1.0, 7.0, -9.0, 2.-0])
Layer_1 = Layer(layer_1_size, inputs)
o_L1 = Layer_1.forward_pass()

TypeError: 'list' object cannot be interpreted as an integer

In [ ]:
layer_2_size = 18
inputs_2 = o_L1
Layer_2 = Layer(layer_2_size, o_L1)
# Layer_2.show_attribute()
o_L2 = Layer_2.forward_pass() 
o_L2

array([ 0.99883664, -0.98511615, -0.99326288,  0.75660914,  0.71835215,
        0.93189981, -0.99927461, -0.99852038,  0.91490985, -0.98437055,
       -0.84702683, -0.08111319, -0.18293876, -0.78488994, -0.89663469,
       -0.7747573 , -0.99984805,  0.98815708])

In [ ]:
layer_3_size = 12
inputs_3 = o_L2
Layer_3 = Layer(layer_3_size, o_L2)
# Layer_2.show_attribute()
o_L3 = Layer_3.forward_pass() 
o_L3

array([-0.28000856, -0.38284641,  0.48349093,  0.76801382,  0.99999288,
        0.99832513, -0.8795215 , -0.99858122, -0.51729256, -0.9047006 ,
        0.99999524, -0.87681524])

In [ ]:
layer_4_size = 4
inputs_4 = o_L3
Layer_4 = Layer(layer_4_size, o_L3)
# Layer_2.show_attribute()
o_L4 = Layer_4.forward_pass() 
o_L4

array([ 0.74515171, -0.38589017,  0.97277526,  0.98443264])

In [ ]:
print(Layer_4.output == o_L4)

[[ True  True  True  True]]


In [ ]:
Layer_4.mean_squared_error(y_true)

[[0.25484829 2.38589017 2.02722474 3.01556736]]
[[0.06494765 5.69247192 4.10964016 9.09364651]]


4.740176558349234

In [ ]:
# Now we are going to backpropagate, calculating the loss with respect to it each weight. 
# Then we will use gradient descent as an optimization algorithm used for minimzing the loss function. 

Layer_4.mean_squared_error(y_true)

[[0.25484829 2.38589017 2.02722474 3.01556736]]
[[0.06494765 5.69247192 4.10964016 9.09364651]]


4.740176558349234

In [ ]:
gradient_4 = Layer_4.backward_pass(y_true)
gradient_4

(array([[ 0.08566917,  0.11713262, -0.147925  , -0.23497535, -0.3059498 ,
         -0.30543955,  0.26909134,  0.3055179 ,  0.15826668,  0.27679494,
         -0.30595052,  0.26826336],
        [ 1.15537903,  1.57971144, -1.99499361, -3.16899984, -4.12619822,
         -4.11931672,  3.62910588,  4.12037342,  2.13446685,  3.7330006 ,
         -4.12620799,  3.61793925],
        [ 0.49681922,  0.67928444, -0.85785802, -1.36268703, -1.77428749,
         -1.77132841,  1.56053511,  1.7717828 ,  0.91783226,  1.6052104 ,
         -1.7742917 ,  1.55573339],
        [ 0.72618377,  0.99288698, -1.25390191, -1.99179332, -2.59341574,
         -2.58909055,  2.28098114,  2.58975471,  1.34156422,  2.34628149,
         -2.59342188,  2.27396264]]),
 array([[-0.30595198, -4.12622761, -1.77430013, -2.59343421]]))

In [ ]:
gradient_3 = Layer_3.backward_pass(o_L4)
gradient_3

ValueError: operands could not be broadcast together with shapes (4,) (1,12) 