In [1]:
import numpy as np 
import pandas as pd

np.random.seed(42)

In [2]:
# class Layer: 
#     def __init__(self, size, loss, grad): 
#         pass 
    
#     def mean_squared_eror(self): 
#         pass 
    
#     def cross_entrophy_loss(self): 
#         pass 
    
#     def backward_pass(self): 
#         pass 
    
    

In [42]:
class Layer:
    
     
    def __init__(self, ammount_of_neurons, inputs): 
        self.inputs = inputs
        self.weight = np.random.randn(ammount_of_neurons, len(inputs))
        self.bias = np.zeros(shape=(1, ammount_of_neurons))
        
    def tanh_activation_function(self, input): 
        output = ((np.exp(input)) - np.exp(-input)) / ((np.exp(input)) + np.exp(-input)) 
        return output 
        
    def forward_pass(self): 
        weighted_sum = np.dot(self.weight, self.inputs) + self.bias 
        output = self.tanh_activation_function(weighted_sum)
        return output.flatten() 
        
    
    def show_attribute(self): 
        print("Input Vector : ", self.inputs)
        print("Weight Matrix: \n", self.weight)
        print("Biases Vector: ", self.bias) 


In [43]:
#Creating an Input Layer of 4 inputs feeding forward into 7 neurons
layer_1_size = 7
inputs = [1.0, 7.0, -9.0, 2.-0]
Layer_1 = Layer(layer_1_size, inputs)
Layer_1.show_attribute()

Input Vector :  [1.0, 7.0, -9.0, 2.0]
Weight Matrix: 
 [[-0.39210815 -1.46351495  0.29612028  0.26105527]
 [ 0.00511346 -0.23458713 -1.41537074 -0.42064532]
 [-0.34271452 -0.80227727 -0.16128571  0.40405086]
 [ 1.8861859   0.17457781  0.25755039 -0.07444592]
 [-1.91877122 -0.02651388  0.06023021  2.46324211]
 [-0.19236096  0.30154734 -0.03471177 -1.16867804]
 [ 1.14282281  0.75193303  0.79103195 -0.90938745]]
Biases Vector:  [[0. 0. 0. 0. 0. 0. 0.]]


In [44]:
# forward pass of the first layer 

o_L1 = Layer_1.forward_pass()
o_L1

array([-1.        ,  1.        , -0.99877575,  0.56584201,  0.97929433,
       -0.10607911, -0.98743165])

In [46]:
layer_2_size = 6 
inputs_2 = o_L1
Layer_2 = Layer(layer_2_size, o_L1)
Layer_2.show_attribute()

Input Vector :  [-1.          1.         -0.99877575  0.56584201  0.97929433 -0.10607911
 -0.98743165]
Weight Matrix: 
 [[ 0.21409374 -1.24573878  0.17318093  0.38531738 -0.88385744  0.15372511
   0.05820872]
 [-1.1429703   0.35778736  0.56078453  1.08305124  1.05380205 -1.37766937
  -0.93782504]
 [ 0.51503527  0.51378595  0.51504769  3.85273149  0.57089051  1.13556564
   0.95400176]
 [ 0.65139125 -0.31526924  0.75896922 -0.77282521 -0.23681861 -0.48536355
   0.08187414]
 [ 2.31465857 -1.86726519  0.68626019 -1.61271587 -0.47193187  1.0889506
   0.06428002]
 [-1.07774478 -0.71530371  0.67959775 -0.73036663  0.21645859  0.04557184
  -0.65160035]]
Biases Vector:  [[0. 0. 0. 0. 0. 0.]]


In [10]:
Layer_2.weight.shape, Layer_2.inputs.shape, Layer_2.bias.shape

((10, 1), (1, 7), (1, 10))