In [62]:
import numpy as np 
import pandas as pd

np.random.seed(42)

In [63]:
class Layer:
     
    def __init__(self, input_size, output_size): 
        
        self.inputs = None 
        self.weight = np.random.randn(output_size, input_size)
        self.bias = np.zeros(shape=(output_size, 1))
        self.output = None 
        
        # derivived instance field 
        self.d_bias = None 
        self.d_weight = None 
        self.d_output = None 
        self.d_input = None 
        
    def forward_pass(self, input):
        self.inputs = input 
        output = np.dot(self.weight , self.inputs) + self.bias
        
        # Clipping the output so that it doesn't overflow when passed into an activation function
        self.output = np.round(output, 5)
        return self.output
        

    def backward_pass(self, d_values): 
        
        self.d_weight = np.dot(self.inputs.T)
        self.d_bias 
        self.d_inputs
        pass
        
    def show_attribute(self): 
        print("Input  : \n", self.inputs)
        print("Weight : \n", self.weight)
        print("Biases : \n", self.bias) 
        print("Output : \n", self.output)

In [64]:
class Activation_Function: 
    
    # Passing in the array/s into the function  
    def tanh_activation_function(self, input): 
        output = np.round(((np.exp(input)) - np.exp(-input)) / ((np.exp(input)) + np.exp(-input)), 5)
        return output 
    
    def d_tanh_activation_function(self, input): 
        output = 1 - ((np.exp(input) - np.exp(-input))**2 / (np.exp(input) + np.exp(-input))**2) 
        return output 

In [65]:
class Mean_Squared_Error: 

    def mean_squared_error(self, y_pred, y_true):
        
        if y_pred.ndim != 1: 
            summed_matrix = y_pred.sum(axis=0)
        else:
            summed_matrix = y_pred 
        self.loss = np.mean((y_true - summed_matrix)**2)
         
        return  self.loss
    
    def d_mean_squared_error(self): 
        pass 


In [66]:
class Stocastic_Gradient_Descent: 
    
    # By default the learning rate is set to one unless its specified 
    def __init__(self, learning_rate=1.0 ):
        self.learning_rate = learning_rate 
        
    def update_parameters(self, layer): 
        layer.weight += -self.learning_rate * layer.d_weight 
        layer.bias += -self.learning_rate * layer.d_bias 
    
    def forward(self): 
        pass 
    
    def backward(self): 
        pass 

        d_loss_output = -2 * (y_true - self.output) 
        d_output_weighted_sum = 1 - ((np.exp(self.output) - np.exp(-self.output))**2 / (np.exp(self.output) + np.exp(-self.output))**2) 
        
        self.d_weight = np.dot((d_loss_output * d_output_weighted_sum ).reshape(-1, 1), self.inputs.reshape(1, -1))
        self.d_bias = d_loss_output * d_output_weighted_sum

        return self.d_weight, self.d_bias
    
    def gradient_descent(self, learning_rate=0.01): 
        self.weight -= learning_rate * self.d_weight 
        self.bias -= learning_rate * self.d_bias.reshape(-1, 1) 

In [88]:
y_true = [1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0]

x_input = [-1.0, 7.0, 2.0, -4.0,], [-1.0, 6.0, 9.0, -4.0], [-2.0, -3.0, 2.0, -5.0] , [7.0, 3.0, 2.0, 0.0]

In [89]:
# Layer(input, output size)
input_layer = Layer(4, 6)
hidden_layer_1 = Layer(6, 12) 
hidden_layer_2 = Layer(12, 8) 
hidden_layer_3 = Layer(8, 6)
output_layer = Layer(6, 4)

In [90]:
# Creating Necessary Objects 
activation = Activation_Function()
compute_loss = Mean_Squared_Error() 

In [91]:
# By calling the activation function on the ouput of the current layer it updates the output. 
input_layer.forward_pass(x_input)
input_layer.output = activation.tanh_activation_function(input_layer.output) 

hidden_layer_1.forward_pass(input_layer.output)
hidden_layer_1.output = activation.tanh_activation_function(hidden_layer_1.output)

hidden_layer_2.forward_pass(hidden_layer_1.output)
hidden_layer_2.output = activation.tanh_activation_function(hidden_layer_2.output)

hidden_layer_3.forward_pass(hidden_layer_2.output)
hidden_layer_3.output = activation.tanh_activation_function(hidden_layer_3.output) 

output_layer.forward_pass(hidden_layer_3.output)
output_layer.output = activation.tanh_activation_function(output_layer.output) 


In [92]:
output_layer.output

array([[-0.69994, -0.6964 ,  0.46767, -0.97558],
       [ 0.51239,  0.51272, -0.97129,  0.70759],
       [-0.91406, -0.91545, -0.69441,  0.98738],
       [-0.4822 , -0.4785 , -0.99897,  0.41728]])

In [103]:
# Since the final output would be viewed as predictions, we will convert all negatives to 0 and all positives to 1
processed_array = np.where(output_layer.output > 0, 1, 0)
summed_array = np.sum(processed_array, axis=0)
bool_array = np.where((summed_array == 0) | (summed_array == 1), False, True)
accuracy = np.mean(bool_array == y_true)



array([[0, 0, 1, 0],
       [1, 1, 0, 1],
       [0, 0, 0, 1],
       [0, 0, 0, 1]])

In [110]:
# Calling a function to compute the loss 
loss = compute_loss.mean_squared_error(output_layer.output, y_true)

# Here we are finding the accuracy. 
# Since the final output would be viewed as probability, we will essentially convert all negatives to false and all positives to true
processed_array = np.where(output_layer.output > 0, 1, 0)
summed_array = np.sum(processed_array, axis=0)
bool_array = np.where((summed_array == 0) | (summed_array == 1), False, True)
accuracy = np.mean(bool_array == y_true)
    
print("Loss: ", loss) 
print("Accuracy: ", accuracy)



Loss:  3.692934555475
Accuracy:  0.25


In [80]:
 np.argmax(output_layer.output, axis=0)
 

array([1, 2, 0, 3])

In [44]:
sgd = Stocastic_Gradient_Descent()

sgd.update_parameters(input_layer)
sgd.update_parameters(hidden_layer_1)
sgd.update_parameters(hidden_layer_2)
sgd.update_parameters(hidden_layer_3)
sgd.update_parameters(output_layer)


TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

In [ ]:
for epochs in range(100): 
    print("step ", epochs, ". Loss: ", ", Accuracy: " )
    pass 
