In [185]:
import numpy as np 
import pandas as pd

np.random.seed(42)

In [206]:
class MLP: 
    
    def __init__(self, batch_size_inputs): 
        self.layer = None
        self.batch_size_inputs = batch_size_inputs 
        
    def forward_pass(self):
        self.layer = self.batch_size_inputs 
        layer_output = []
        for layers in self.batch_size_inputs: 
            layer_output.append(Layer.forward_pass(layers))
        
        return print(layer_output)

class Layer:
     
    def __init__(self, input_size, output_size): 
        
        self.inputs = None 
        self.weight = np.random.randn(output_size, input_size)
        self.bias = np.zeros(shape=(output_size, 1))
        self.output = None 
        
        # derivived instance field 
        self.d_bias = None 
        self.d_weight = None 
    
    def show_attribute(self): 
        print("Input  : \n", self.inputs)
        print("Weight : \n", self.weight)
        print("Biases : \n", self.bias) 
        print("Output : \n", self.output)
        
    def tanh_activation_function(self, input): 
        output = ((np.exp(input)) - np.exp(-input)) / ((np.exp(input)) + np.exp(-input)) 
        return output 
        
    def forward_pass(self, input):
        self.inputs = input 
        weighted_sum = np.dot(self.weight , self.inputs) + self.bias 
        # self.output = self.tanh_activation_function(weighted_sum)
        
        self.output = weighted_sum
        return self.output
        
        # return self.output.flatten() 
    
    def mean_squared_error(self, y_true):
        self.loss = np.mean((y_true - self.output)**2)
        print(y_true - self.output)
        print((y_true - self.output)**2) 
        return  self.loss
    
    def backward_pass(self, y_true): # Compute the loss function with respect to each weight. 
        d_loss_output = -2 * (y_true - self.output) 
        d_output_weighted_sum = 1 - ((np.exp(self.output) - np.exp(-self.output))**2 / (np.exp(self.output) + np.exp(-self.output))**2) 
        
        self.d_weight = np.dot((d_loss_output * d_output_weighted_sum ).reshape(-1, 1), self.inputs.reshape(1, -1))
        self.d_bias = d_loss_output * d_output_weighted_sum

        return self.d_weight, self.d_bias
    
    def gradient_descent(self, learning_rate=0.01): 
        self.weight -= learning_rate * self.d_weight 
        self.bias -= learning_rate * self.d_bias.reshape(-1, 1) 
    
    


SyntaxError: '(' was never closed (4104724600.py, line 13)

In [204]:
y_true = [1.0, 2.0, 3.0, 4.0]
x_input = [-1.0, 7.0, 2.0, -4.0], [-1.0, 6.0, 9.0, -4.0], [-2.0, -3.0, 2.0, -5.0] , [7.0, 3.0, 2.0, 0.0]

In [205]:
input_layer = Layer(4, 6)
hidden_layer_1 = Layer(6, 12) 
hidden_layer_2 = Layer(12, 7) 
output_Layer = Layer(7, 4)

mlp = MLP(x_input)

mlp.forward_pass()

TypeError: Layer.forward_pass() missing 1 required positional argument: 'input'

In [ ]:
output_1 = 

In [180]:
output_1 = input_layer.forward_pass(x_input)

AttributeError: 'tuple' object has no attribute 'T'

In [147]:
input_layer.inputs , input_layer.weight.shape

([-1.0, 7.0, 2.0, -4.0], (6, 4))

________________
PIVOT

In [148]:
#Creating an Input Layer of 4 inputs feeding forward into 7 neurons
layer_1_size = 7
inputs = ([1.0, 7.0, -9.0, 2.-0])
Layer_1 = Layer(layer_1_size, inputs)
o_L1 = Layer_1.forward_pass()

TypeError: 'list' object cannot be interpreted as an integer

In [ ]:
layer_2_size = 18
inputs_2 = o_L1
Layer_2 = Layer(layer_2_size, o_L1)
# Layer_2.show_attribute()
o_L2 = Layer_2.forward_pass() 
o_L2

array([ 0.99883664, -0.98511615, -0.99326288,  0.75660914,  0.71835215,
        0.93189981, -0.99927461, -0.99852038,  0.91490985, -0.98437055,
       -0.84702683, -0.08111319, -0.18293876, -0.78488994, -0.89663469,
       -0.7747573 , -0.99984805,  0.98815708])

In [ ]:
layer_3_size = 12
inputs_3 = o_L2
Layer_3 = Layer(layer_3_size, o_L2)
# Layer_2.show_attribute()
o_L3 = Layer_3.forward_pass() 
o_L3

array([-0.28000856, -0.38284641,  0.48349093,  0.76801382,  0.99999288,
        0.99832513, -0.8795215 , -0.99858122, -0.51729256, -0.9047006 ,
        0.99999524, -0.87681524])

In [ ]:
layer_4_size = 4
inputs_4 = o_L3
Layer_4 = Layer(layer_4_size, o_L3)
# Layer_2.show_attribute()
o_L4 = Layer_4.forward_pass() 
o_L4

array([ 0.74515171, -0.38589017,  0.97277526,  0.98443264])

In [ ]:
print(Layer_4.output == o_L4)

[[ True  True  True  True]]


In [ ]:
Layer_4.mean_squared_error(y_true)

[[0.25484829 2.38589017 2.02722474 3.01556736]]
[[0.06494765 5.69247192 4.10964016 9.09364651]]


4.740176558349234

In [ ]:
# Now we are going to backpropagate, calculating the loss with respect to it each weight. 
# Then we will use gradient descent as an optimization algorithm used for minimzing the loss function. 

Layer_4.mean_squared_error(y_true)

[[0.25484829 2.38589017 2.02722474 3.01556736]]
[[0.06494765 5.69247192 4.10964016 9.09364651]]


4.740176558349234

In [ ]:
gradient_4 = Layer_4.backward_pass(y_true)
gradient_4

(array([[ 0.08566917,  0.11713262, -0.147925  , -0.23497535, -0.3059498 ,
         -0.30543955,  0.26909134,  0.3055179 ,  0.15826668,  0.27679494,
         -0.30595052,  0.26826336],
        [ 1.15537903,  1.57971144, -1.99499361, -3.16899984, -4.12619822,
         -4.11931672,  3.62910588,  4.12037342,  2.13446685,  3.7330006 ,
         -4.12620799,  3.61793925],
        [ 0.49681922,  0.67928444, -0.85785802, -1.36268703, -1.77428749,
         -1.77132841,  1.56053511,  1.7717828 ,  0.91783226,  1.6052104 ,
         -1.7742917 ,  1.55573339],
        [ 0.72618377,  0.99288698, -1.25390191, -1.99179332, -2.59341574,
         -2.58909055,  2.28098114,  2.58975471,  1.34156422,  2.34628149,
         -2.59342188,  2.27396264]]),
 array([[-0.30595198, -4.12622761, -1.77430013, -2.59343421]]))

In [ ]:
gradient_3 = Layer_3.backward_pass(o_L4)
gradient_3

ValueError: operands could not be broadcast together with shapes (4,) (1,12) 