In [1]:
import numpy as np 
import pandas as pd

In [15]:
class Input_Layer:
    
    def __init__(self, size, inputs): 
        self.inputs = inputs
        self.weight = np.random.randn(size, len(inputs))
        self.bias = np.random.randn(size) * 10
        
    def show_attribute(self): 
        print("Input Vector : ", self.inputs)
        print("Weight Matrix: \n", self.weight)
        print("Biases Vector: ", self.bias) 

    def forward_pass(self): 
        self.inputs.reshape(1, 7)
        
        output = np.dot(self.inputs * self.weight.T + self.bias)
        return output

In [16]:
#Creating an Input Layer 

layer_size = 7
inputs = [1.0, 7.0, -9.0, 2.-0]

Layer1 = Input_Layer(layer_size, inputs)
Layer1.show_attribute()

Input Vector :  [1.0, 7.0, -9.0, 2.0]
Weight Matrix: 
 [[ 0.34201596  0.78478959  0.44007022  0.31981382]
 [-1.01900058  1.87940734  0.57921522 -0.35907658]
 [-1.09049753 -1.67202728 -0.73093016 -2.08909825]
 [-2.27758371  2.10359881 -2.52282102 -0.83677389]
 [-0.28165232  0.1578732  -1.96691929  0.33655439]
 [-1.02254245 -1.74373826  0.955592    0.75445595]
 [-0.94840562 -1.27403113 -1.17912051 -1.21884027]]
Biases Vector:  [  3.18681035  -4.20622282   4.23039963  -4.62524379  -7.82853942
   2.10572712 -14.75705155]


In [17]:
Layer1.forward_pass()

AttributeError: 'list' object has no attribute 'reshape'