In [95]:
import numpy as np 
import pandas as pd

np.random.seed(42)

In [96]:
class Layer:
     
    def __init__(self, input_size, output_size): 
        
        self.inputs = None 
        # self.weight = np.random.randn(output_size, input_size)
        self.weight = np.random.uniform(-10, 10, (output_size, input_size))
        # self.bias = np.zeros(shape=(output_size, 1))
        self.bias = np.random.rand(output_size, 1)

        self.output = None 
        
        # derivived instance field 
        self.d_bias = None 
        self.d_weight = None 
        self.d_output = None 
        self.d_input = None 
        
    def forward_pass(self, input):
        self.inputs = input 
        output = np.dot(self.weight , self.inputs) + self.bias
        
        # Clipping the output so that it doesn't overflow when passed into an activation function
        self.output = np.round(output, 5)
        return self.output
        

    def backward_pass(self, d_values): 
        
        self.d_weight = np.dot(self.inputs.T)
        self.d_bias 
        self.d_inputs
        pass
        
    def show_attribute(self): 
        print("Input  : \n", self.inputs)
        print("Weight : \n", self.weight)
        print("Biases : \n", self.bias) 
        print("Output : \n", self.output)

In [97]:

class Activation_Function: 
    
    # Passing in the array/s into the function  
    def tanh_activation_function(self, input): 
        output = np.round(((np.exp(input)) - np.exp(-input)) / ((np.exp(input)) + np.exp(-input)), 5)
        return output 
    
    def d_tanh_activation_function(self, input): 
        output = 1 - ((np.exp(input) - np.exp(-input))**2 / (np.exp(input) + np.exp(-input))**2) 
        return output 
    
    def sigmoid_activation_function(self, input): 
        output = 1/(1 + np.exp(-(input)))
        return output 

In [98]:
class Binary_Cross_Entropy: 
    
    def binary_cross_entropy(self, y_pred, y_true):
        
        # Calculate binary cross entropy loss
        self.loss = -np.mean(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))
        
        return self.loss 

In [99]:
class Mean_Squared_Error: 

    def mean_squared_error(self, y_pred, y_true):
        
        if y_pred.ndim != 1: 
            summed_matrix = y_pred.sum(axis=0)
        else:
            summed_matrix = y_pred 
        self.loss = np.mean((y_true - summed_matrix)**2)
         
        return  self.loss
    

In [100]:
class Stocastic_Gradient_Descent: 
    
    # By default the learning rate is set to one unless its specified 
    def __init__(self, learning_rate=1.0 ):
        self.learning_rate = learning_rate 
        
    def update_parameters(self, layer): 
        layer.weight += -self.learning_rate * layer.d_weight 
        layer.bias += -self.learning_rate * layer.d_bias 
    
    def forward(self): 
        pass 
    
    def backward(self): 
        pass 

        d_loss_output = -2 * (y_true - self.output) 
        d_output_weighted_sum = 1 - ((np.exp(self.output) - np.exp(-self.output))**2 / (np.exp(self.output) + np.exp(-self.output))**2) 
        
        self.d_weight = np.dot((d_loss_output * d_output_weighted_sum ).reshape(-1, 1), self.inputs.reshape(1, -1))
        self.d_bias = d_loss_output * d_output_weighted_sum

        return self.d_weight, self.d_bias
    
    def gradient_descent(self, learning_rate=0.01): 
        self.weight -= learning_rate * self.d_weight 
        self.bias -= learning_rate * self.d_bias.reshape(-1, 1) 

In [101]:
# Make a mini MLP, 3 layers only

y_true = [1, 0, 1, 1]
x_input = [1], [1], [0], [1] 

In [102]:
input_layer = Layer(4, 4) 
hidden_layer = Layer(4, 4) 
output_layer = Layer(4, 1) 

act_func = Activation_Function() 

In [103]:
input_layer.inputs

In [104]:
input_layer.forward_pass(x_input) 
input_layer.show_attribute()

Input  : 
 ([1], [1], [0], [1])
Weight : 
 [[-2.50919762  9.01428613  4.63987884  1.97316968]
 [-6.87962719 -6.88010959 -8.83832776  7.32352292]
 [ 2.02230023  4.16145156 -9.58831011  9.39819704]
 [ 6.64885282 -5.75321779 -6.36350066 -6.3319098 ]]
Biases : 
 [[0.30424224]
 [0.52475643]
 [0.43194502]
 [0.29122914]]
Output : 
 [[ 8.7825 ]
 [-5.91146]
 [16.01389]
 [-5.14505]]


In [38]:
act_func.sigmoid_activation_function(input_layer.output)

array([[0.69430426, 0.72064233, 0.64604057, 0.48464483],
       [0.35974525, 0.30746021, 0.73239932, 0.20584258],
       [0.03613184, 0.21880737, 0.1259668 , 0.08292977],
       [0.87683242, 0.62078701, 0.86156385, 0.79909377]])

In [312]:
y_true = [1.0, 1.0, 1.0, -1.0, 1.0, 1.0, -1.0, 1.0, 1.0, 1.0]

x_input = [ 1.0, -1.0,  1.0,  1.0,  1.0,  1.0, -1.0,  1.0,  1.0, -1.0], [-1.0, -1.0,  1.0, -1.0, -1.0, -1.0,  1.0,  1.0, -1.0, -1.0], [ 1.0,  1.0, -1.0,  1.0, -1.0,  1.0, -1.0,  1.0, -1.0,  1.0] , [ 1.0, -1.0,  1.0, -1.0,  1.0, -1.0, -1.0,  1.0, -1.0,  1.0]

# Forward Pass

In [313]:
# Layer(input vector, output vector)
input_layer = Layer(4, 12)
hidden_layer_1 = Layer(12, 12) 
hidden_layer_2 = Layer(12, 8) 
hidden_layer_3 = Layer(8, 6)
output_layer = Layer(6, 4)

In [314]:
# Creating Necessary Objects 
activation = Activation_Function()
loss_activation = Binary_Cross_Entropy() 

In [315]:
# By calling the activation function on the ouput of the current layer it updates the output. 
input_layer.forward_pass(x_input)
input_layer.output = activation.sigmoid_activation_function(input_layer.output) 

hidden_layer_1.forward_pass(input_layer.output)
hidden_layer_1.output = activation.sigmoid_activation_function(hidden_layer_1.output)

hidden_layer_2.forward_pass(hidden_layer_1.output)
hidden_layer_2.output = activation.sigmoid_activation_function(hidden_layer_2.output)

hidden_layer_3.forward_pass(hidden_layer_2.output)
hidden_layer_3.output = activation.sigmoid_activation_function(hidden_layer_3.output) 

output_layer.forward_pass(hidden_layer_3.output)
output_layer.output = activation.sigmoid_activation_function(output_layer.output) 


In [316]:
output_layer.output

array([[0.7458197 , 0.74333975, 0.74187944, 0.74439338, 0.7435057 ,
        0.74439338, 0.74131988, 0.74324244, 0.7477598 , 0.745723  ],
       [0.77618655, 0.76020249, 0.77991824, 0.76286654, 0.78092073,
        0.76286654, 0.76656038, 0.76512037, 0.78210062, 0.77112421],
       [0.13465993, 0.14367453, 0.13283978, 0.1411562 , 0.13217194,
        0.1411562 , 0.14264904, 0.13843615, 0.13574145, 0.13727379],
       [0.8168874 , 0.81355542, 0.81295857, 0.8111592 , 0.81478093,
        0.8111592 , 0.80969352, 0.81244712, 0.81071151, 0.818775  ]])

In [317]:
# Since the final output would be viewed as predictions, we will convert all negatives to 0 and all positives to 1
processed_array = np.where(output_layer.output > 0, 1, 0)
summed_array = np.sum(processed_array, axis=0)
bool_array = np.where((summed_array == 0) | (summed_array == 1), False, True)
accuracy = np.mean(bool_array == y_true)



In [318]:
output_layer.output

array([[0.7458197 , 0.74333975, 0.74187944, 0.74439338, 0.7435057 ,
        0.74439338, 0.74131988, 0.74324244, 0.7477598 , 0.745723  ],
       [0.77618655, 0.76020249, 0.77991824, 0.76286654, 0.78092073,
        0.76286654, 0.76656038, 0.76512037, 0.78210062, 0.77112421],
       [0.13465993, 0.14367453, 0.13283978, 0.1411562 , 0.13217194,
        0.1411562 , 0.14264904, 0.13843615, 0.13574145, 0.13727379],
       [0.8168874 , 0.81355542, 0.81295857, 0.8111592 , 0.81478093,
        0.8111592 , 0.80969352, 0.81244712, 0.81071151, 0.818775  ]])

In [319]:
np.log(np.round(output_layer.output,3))

array([[-0.29302968, -0.29705923, -0.29840604, -0.29571424, -0.29571424,
        -0.29571424, -0.29975465, -0.29705923, -0.2903523 , -0.29302968],
       [-0.25360276, -0.27443685, -0.24846136, -0.27049725, -0.24718013,
        -0.27049725, -0.26526848, -0.26787945, -0.24590054, -0.26006691],
       [-2.0024805 , -1.93794198, -2.01740615, -1.95899539, -2.02495336,
        -1.95899539, -1.94491065, -1.98050159, -1.99510039, -1.98777435],
       [-0.20211618, -0.20579491, -0.20702417, -0.20948722, -0.20456717,
        -0.20948722, -0.21072103, -0.20825494, -0.20948722, -0.1996712 ]])

In [320]:
# Calling a function to compute the loss 
loss = loss_activation.binary_cross_entropy(output_layer.output, y_true)

# Here we are finding the accuracy. 
# Since the final output would be viewed as probability, we will essentially convert all negatives to false and all positives to true
processed_array = np.where(output_layer.output > 0, 1, 0)
summed_array = np.sum(processed_array, axis=0)
bool_array = np.where((summed_array == 0) | (summed_array == 1), False, True)
accuracy = np.mean(bool_array == y_true)
    
print("Loss: ", loss) 
print("Accuracy: ", accuracy)



TypeError: unsupported operand type(s) for -: 'int' and 'list'

# Backward Pass

In [ ]:
optimizer = Stocastic_Gradient_Descent()

In [ ]:
loss_activation.backward(output_layer.output, layer)

In [ ]:


optimizer.update_parameters(input_layer)
optimizer.update_parameters(hidden_layer_1)
optimizer.update_parameters(hidden_layer_2)
optimizer.update_parameters(hidden_layer_3)
optimizer.update_parameters(output_layer)


TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

In [ ]:
for epochs in range(100): 
    print("step ", epochs, ". Loss: ", ", Accuracy: " )
    pass 
